# Generated by Django 3.1.2 on 2020-10-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_delete_historicaluser'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='is_active',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Published'), (1, 'Pending Approval'), (2, 'Scheduled to Publish'), (9, 'Published')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Published'), (1, 'Pending Approval'), (2, 'Scheduled to Publish'), (9, 'Published')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
